### ISSUE TITLE
Bug [1.19.2]: Aether Redux entirely removes the Aether dimension

### ISSUE THREAD

**Issue by GeminiCrafterMan** [Zepalesque/Aether-Redux-Issue-Tracker#10]
**What version of the mod, Forge/Neoforge and Minecraft are you using?**
Mod: Release 1.0.5-1.19.2
Forge: 43.3.0
Minecraft: 1.19.2

**Describe the bug**
Exactly as the title states. Adding Aether Redux to my mod pack entirely removed the Aether dimension from the list. JourneyMap doesn't show it, portals to the Aether simply don't work in survival _or_ creative, and it's impossible to use commands to teleport there. `/execute in` doesn't show the dimension in the list, only vanilla's and Blue Skies's.

**To Reproduce**
1. Install the Aether mod.
2. Install Aether Redux.
3. Try to travel to the Aether by any means.

**Expected behavior**
I should be able to go to the Aether to see _literally anything_ this mod has to offer.

**Screenshots**
![image](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/assets/8532523/3eaa6bb2-0c03-494a-b83e-e840889f1391)
Edit: added another screenshot of the issue
![image](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/assets/8532523/1e93c057-c37f-42e1-858c-f9f1084b68bf)
Edit 2: Tried again on a fresh modpack, issue still persists.
![image](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/assets/8532523/1f0f993e-2d67-4d6d-981c-21f8fb5da433)

**Crash report (if necessary and/or applicable)**
N/A

**Log file (should be titled latest.log, if applicable)**
https://mclo.gs/MjGiyob
Edit: that was the wrong log. here's the correct one.
https://mclo.gs/LaMXtGl
Edit 2: Tried again on a fresh modpack, issue still persists. This should be more readable than the mess above.
https://mclo.gs/Y1KCCDZ

**Additional context**
N/A

**Comment by Zepalesque** [comment]
This happens sometimes on 1.19.2 (a general minecraft issue afaik, not redux _or_ the aether causing it), if this _is_ that same issue, then relogging/saving and re-entering the world should fix it

If that _doesn’t_ work though, I’ll look into it for the next update

**Comment by GeminiCrafterMan** [comment]
I mean, it _kind of_ worked? I managed to get into the Aether permanently for one session by messing around and disabling the mod, standing in the portal, re-enabling it... something like that. I don't understand how it managed to magically start working.

**Comment by GeminiCrafterMan** [comment]
Oops -- accidentally closed the issue! GitHub's buttons are kinda confusing in their placement sometimes.

**Comment by Zepalesque** [comment]
Hmm, what other mods are you using? I haven't had this happen where just saving and exiting to the title and then going back into the world didn't fix it, so a mod conflict seems likely if that didn't work

**Comment by GeminiCrafterMan** [comment]
In the fresh pack, there were none other than AR and its dependencies, but maybe I didn't test thoroughly enough there.

**Comment by Zepalesque** [comment]
oh nice! If it stops working again then you can reopen the issue, but since it seems to have stopped happening I'll close the issue for now
