### ISSUE TITLE
where is the subzero crossbow

### ISSUE THREAD

**Issue by GreenForzeGaming** [Zepalesque/Aether-Redux-Issue-Tracker#101]
### Minecraft Version

?

### Mod Version

?

### Forge/Neoforge Version

?

### What happened?

?

### What was the expected result?

?

### Steps to Reproduce

?

### Log Output (if applicable)

?

### Crash Report (if applicable)

?

### Is this a compatibility issue with another mod?

?

### Additional Context/Information

?

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
Please fill in the template properly - there is a reason that you're supposed to fill them in, I can't know what the issue is otherwise

'where is the subzero crossbow' doesn't tell me what's wrong, if it's missing from somewhere, whether it's the creative tab or dungeon chests, please open an issue that properly reports the issue

**Comment by GreenForzeGaming** [comment]
i cant seem to find it is what im asking. there is no wiki so i have no clue where items are

> Please fill in the template properly - there is a reason that you're supposed to fill them in, I can't know what the issue is otherwise
> 
> 'where is the subzero crossbow' doesn't tell me what's wrong, if it's missing from somewhere, whether it's the creative tab or dungeon chests, please open an issue that properly reports the issue

**Comment by Zepalesque** [comment]
ah I see, ok yeah it should be in the gold dungeon loot chests then
I should probably put that somewhere at some point, maybe in the book of lore entry
