### ISSUE TITLE
Missing lang entries for boat entities

### ISSUE THREAD

**Issue by VoidLeech** [Zepalesque/Aether-Redux-Issue-Tracker#104]
The language keys are visible using WAILA-style mods.
Version: 1.20.1-2.0.11
This concerns all the boats added by this mod:
 - entity.aether_redux.{wood_type}_boat
 - entity.aether_redux.{wood_type}_chest_boat

**Comment by Zepalesque** [comment]
hmm, will be fixed in 2.0.12
