### ISSUE TITLE
[Bug]: Missing Texture for Jellyshroom Chest Boat

### ISSUE THREAD

**Issue by VoidLeech** [Zepalesque/Aether-Redux-Issue-Tracker#105]
### Minecraft Version

1.20.1

### Mod Version

2.0.11

### Forge/Neoforge Version

Forge 47.2.0

### What happened?

Placed all boats to report the missing lang entries and noticed this boat (and only this boat) had missing textures: 
![2024-05-03_01 49 25](https://github.com/Zepalesque/The-Aether-Redux/assets/57987812/9cba7425-b022-4da6-9952-89c5fa77e51c)

### What was the expected result?

Jellyshroom Chest Boat to appear as the Jellyshroom Boat, but with a chest.

### Steps to Reproduce

Place Jellyshroom Chest Boat

### Log Output (if applicable)

https://mclo.gs/5oJNXro
Line 892 onward alludes to a missing texture file: 
> [03May2024 01:48:47.268] [Render thread/WARN] [net.minecraft.client.renderer.texture.TextureManager/]: Failed to load texture: aether_redux:textures/entity/chest_boat/jellyshroom.png
java.io.FileNotFoundException: aether_redux:textures/entity/chest_boat/jellyshroom.png

The file in question is still uses [springshroom](https://github.com/Zepalesque/The-Aether-Redux/blob/1.20.1/src/main/resources/assets/aether_redux/textures/entity/chest_boat/springshroom.png).

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
uh oh, I forgot to rename the texture when I renamed jellyshroom from springshroom lol
will be fixed in 2.0.12

**Comment by VoidLeech** [comment]
I think this and the other boat issue can be closed now (:
