### ISSUE TITLE
[Bug]: Valkyrie Ring drops in stacks of two

### ISSUE THREAD

**Issue by Lucipo** [Zepalesque/Aether-Redux-Issue-Tracker#107]
### Minecraft Version

1.20.1

### Mod Version

2.0.12b

### Forge/Neoforge Version

47.2.21

### What happened?

Valkyries drop valkyrie rings in stacks of 2 upon death

### What was the expected result?

Should be stacks of one due to it's rarity and how powerful it is when worn

### Steps to Reproduce

1: Get looting 3 weapon
2: Kill valkyrie until it drops rings
3: Pick it up and its a stack of two

### Log Output (if applicable)

[latest.log](https://github.com/Zepalesque/The-Aether-Redux/files/15215609/latest.log)

### Additional Context/Information

https://medal.tv/games/minecraft/clips/2bwFqpHlQzcb_N/d1337lx6kMJC?invite=cr-MSxIQjQsMTA1ODAwNzcs

Clip of it happening

Also note im on sinytra connector, but using the mod's forge version

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Lucipo** [comment]
Also this isnt an issue but I feel the item, due to how powerful and game-changing it is, should be like extremely rare. 1/750 or something, so that three stacking the rings would mean you would have to combat a great deal of rng and grind OR just use valkyrie weapons

**Comment by Zepalesque** [comment]
hmm, odd
and yeah I can decrease the chance
maybe not quite *that* much though, that feels a bit much, especially considering I’m *pretty* sure each silver dungeon has a limited number of valkyries (I’m pretty sure only the trap blocks spawn them)
but yeah I can decrease the chance, right now it’s 3.5%, so around 1/30, I can probably decrease it to somewhere from around 0.5% to 1.5%

**Comment by Zepalesque** [comment]
should be fixed in 2.0.13
