### ISSUE TITLE
[Crash] 1.20.1-2.0.13- Crashes when trying to enter existing world, ticking entity

### ISSUE THREAD

**Issue by PhweeDev** [Zepalesque/Aether-Redux-Issue-Tracker#110]
### Minecraft Version

1.20.1

### Mod Version

2.0.13

### Forge/Neoforge Version

47.2.32

### What happened?

After updating the mod and trying to enter a pre-existing world, it says "joining world" but then turns to "saving world" due to a ticking entity crash. 

### What was the expected result?

The world would load normally. 

### Steps to Reproduce

Not exactly sure how to reproduce as you'd need my modpack. but the log seems to call a bug between Re:Avaritia, an Avaritia fork and Redux. 

### Log Output (if applicable)

[2024-05-14-2.log](https://github.com/Zepalesque/The-Aether-Redux/files/15324497/2024-05-14-2.log)

### Crash Report (if applicable)

[crash-2024-05-14_15.18.33-client.txt](https://github.com/Zepalesque/The-Aether-Redux/files/15324498/crash-2024-05-14_15.18.33-client.txt)

### Is this a compatibility issue with another mod?

I think(?)

### Additional Context/Information

Before you ask, Sinytra Connector isn't the problem.

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
hmm, I’ll look into it for 2.0.14 (or 2.0.13b, whichever the next update ends up being lol)

**Comment by Zepalesque** [comment]
hmm, I can't seem to reproduce the issue with just redux and avarita, could you try to narrow down what mod is causing the crashing?

**Comment by PhweeDev** [comment]
I'm having a hard time figuring out the culprit myself. Not sure how to help contribute to this haha

**Comment by Zepalesque** [comment]
ah, yeah, makes sense
I might have to look into this for a future update, in part due to the gigantic modlist that the log shows 😅, but at some point I can probably try to see if I can reproduce the issue with the same modlist and narrow it down

**Comment by Zepalesque** [comment]
although, just to confirm, the bug happens with redux and doesn’t without redux?

**Comment by PhweeDev** [comment]
Yep, happens only when Redux is in 2.0.13, not when it is in 2.0.12b

**Comment by Zepalesque** [comment]
this is really odd, even when looking at the differences between 2.0.13 and 2.0.12b I can't tell *why on earth* this would be happening, weird

**Comment by PhweeDev** [comment]
Well, I'm not sure why it did that, but it works with 2.0.16, so good enough for me! Thanks for your work!
