### ISSUE TITLE
[Feature Request]: Compatibility With new Aether Team Addons 'Protect Your Moa' and 'Treasure Reforged'

### ISSUE THREAD

**Issue by 2468cool** [Zepalesque/Aether-Redux-Issue-Tracker#115]
### What is your request?

The new addons add in recipes that use enchanted gravitite. I think overriding the recipes to use this mod's gravitite would be beneficial. Also, the Protect Your Moa mod adds Moa armor that does not visually work with the updated Moa models in this mod.

### Why do you think the feature should be added?

Having compatibility with the official new Aether addons would enhance the experience of the game for the player. Players who just get the addons while having this mod would not be able to experience the two new addons.

### Please also confirm the following before submitting the request:

- [X] This suggestion is not a duplicate
- [X] This suggestion fits nicely with the rest of the mod

**Comment by Zepalesque** [comment]
will be in 2.0.15

**Comment by Zepalesque** [comment]
now *is* in 2.0.15 :D

**Comment by Lucky-56** [comment]
using *2.0.15* recipes still use Enchanted Gravitite
![image](https://github.com/Zepalesque/The-Aether-Redux/assets/55949451/4e6c5693-781f-4335-bfe6-3e6ff26e8bbf)

only the smithing templates tho
