### ISSUE TITLE
[Bug]: Using Redux alongside Ancient prevents campfire extinguishing, torch removal, etc.

### ISSUE THREAD

**Issue by BabblingFishes** [Zepalesque/Aether-Redux-Issue-Tracker#117]
### Minecraft Version

1.20.1

### Mod Version

2.0.15

### Forge/Neoforge Version

47.1.105

### What happened?

When in the Aether, it allows me to place torches, campfires, etc, which all stay lit. (It should prevent me from doing this so that I have to use ambrosium torches.)

### What was the expected result?

The Aether prevents me from placing regular torches.

### Steps to Reproduce

1. Go to the Aether.
2. Place a torch.

### Log Output (if applicable)

[latest.log](https://github.com/Zepalesque/The-Aether-Redux/files/15403922/latest.log)
(I did not see anything that looked relevant.)

### Is this a compatibility issue with another mod?

Ancient Aether 0.9.6

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
what version of ancient aether are you using? iirc it was fixed on their end recently

**Comment by Zepalesque** [comment]
closing as it was fixed on AA’s side
