### ISSUE TITLE
[Feature Request]: Please add Universal Enchants compatibility

### ISSUE THREAD

**Issue by mortal-immortal** [Zepalesque/Aether-Redux-Issue-Tracker#118]
### What is your request?

https://www.curseforge.com/minecraft/mc-mods/universal-enchants-forge

Can you add compatibility for that mod?

subzero crossbow's enchantment is not applied properly.

Power, Infinity

### Why do you think the feature should be added?

To support a wider range of modpacks

### Please also confirm the following before submitting the request:

- [X] This suggestion is not a duplicate
- [X] This suggestion fits nicely with the rest of the mod

**Comment by Zepalesque** [comment]
I’d suggest reporting/suggesting this on their issue tracker, since then if they change anything about their api stuff it won’t break compat until I could fix it
https://github.com/Fuzss/universalenchants/issues

**Comment by Zepalesque** [comment]
closing as I have opened a report on their end, hopefully will be implemented sometime in the future to the universal enchants mod itself
