### ISSUE TITLE
[Bug]: JEI tooltip error (possible mod conflict)

### ISSUE THREAD

**Issue by DarkPhoenixCoding** [Zepalesque/Aether-Redux-Issue-Tracker#119]
### Minecraft Version

1.20.1

### Mod Version

2.1.15

### Forge/Neoforge Version

47.2.0

### What happened?

There is an issue related to JEI likely caused by a conflict with another mod. As of writing, I have yet to find which mod(s) is causing the conflict, and I don't have all the time in the world to find which one it is, so I'll just provide the entire mod list in a text file for people to work with. The modpack I'm working on is heavily aether-based, so this is a huge problem for me.

In JEI menus, all items say "tooltip error, see logs" with no additional information.

[mods.txt](https://github.com/Zepalesque/The-Aether-Redux/files/15448966/mods.txt)

I would provide the entire mod folder, but it's too big for github.

### What was the expected result?

Normal JEI items?

### Steps to Reproduce

1. Install every mod I have listed (That's the best method I have devised until I can find the conflict)
2. Enter any world.
3. Open inventory and hover over any item in the JEI interface.

Repeat with and without Redux enabled. I don't know what is causing the conflict yet.

### Log Output (if applicable)

[latest.log](https://github.com/Zepalesque/The-Aether-Redux/files/15449015/latest.log)

### Is this a compatibility issue with another mod?

Don't know yet

### Additional Context/Information

Again, I would provide the entire mod folder, but that's too big for Github, apparently.

![2024-05-26_15 29 19](https://github.com/Zepalesque/The-Aether-Redux/assets/26417642/147ba165-ea25-4746-a3ae-2c33cacf3dda)

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [ ] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
Based on the log, this seems to be an issue with the Delightful mod (which has compact with redux) so I’d suggest reporting it to their issue tracker

**Comment by Zepalesque** [comment]
did not mean to close the issue

**Comment by Zepalesque** [comment]
can’t remember why I was keeping this open as it’s likely a Delightful issue as I said before, so I’ll just close this
