### ISSUE TITLE
Bug [1.20.1]: Sentry Ring's double jump does not work

### ISSUE THREAD

**Issue by TheGag96** [Zepalesque/Aether-Redux-Issue-Tracker#12]
**What version of the mod, Forge/Neoforge and Minecraft are you using?**
* Aether Redux: 1.19.4
* Forge: 42.2.1
* Minecraft: 1.20.1

**Describe the bug**
With the Sentry Ring equipped, attempting to double jump does not make the player jump again. The advancement is granted, but nothing otherwise happens.

**To Reproduce**
1. Equip the Sentry Ring.
2. Attempt to double jump.

**Expected behavior**
The player jumps again in the air.

**Comment by Zepalesque** [comment]
Do you have any other mods installed? I can't seem to reproduce the issue
Also, you put `1.19.4` for the Redux version, my guess is it's due to an issue in the mods.toml file, but can you check the file name? It should most likely be either 1.0.1 or 1.0

**Comment by TheGag96** [comment]
The filename is `aether-redux-1.0.1-1.20.1-neoforge.jar`. Truth be told, my Sentry Ring has been working just fine the past few hours of play. Not sure what was going on the first time... Perhaps I should close?

**Comment by Zepalesque** [comment]
Sure, if it starts happening again nd you notice something specific causing it then you could probably reopen it but for now it’s probably fine being closed
