### ISSUE TITLE
[Bug]: i cant use the pheonix ring.

### ISSUE THREAD

**Issue by davros364** [Zepalesque/Aether-Redux-Issue-Tracker#120]
### Minecraft Version

1.20.1

### Mod Version

1.20.1

### Forge/Neoforge Version

1.253.0.17952

### What happened?

im trying to get the pyromaniac acheivement, but when i use a fireball anywhere except the overworld or the suns spirit boss arena it just says im not in the right enviroment to use it. i have the ring equipped, but the only other way it can work is with the afterburner but it doesnt give me the achievemt.

### What was the expected result?

to hopefully kill a sheepuff with a fireball using the pheonix ring and eventually get the pyromaniac acheivement.

### Steps to Reproduce

just using a firechare in the aether with the pheonix ring equipped.

### Additional Context/Information

![Screenshot 2024-06-02 182035](https://github.com/Zepalesque/The-Aether-Redux/assets/171524878/e690fecd-70aa-492e-863c-566548f425f3)
![Screenshot 2024-06-02 182050](https://github.com/Zepalesque/The-Aether-Redux/assets/171524878/66cd49b2-7195-4712-bbb4-fe9aba2f8f8c)
!

### Make sure to confirm these as well before submitting the report:

- [x] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
the phoenix ring was replaced with a new item called the solar emblem a while ago, I suggest you update your version to the latest one, as I believe I fixed this in version 2.0

(also another thing, for the issue report itself, 1.20.1 isn’t the mod’s version, in your case it’d likely be something like 1.3.4)

**Comment by Zepalesque** [comment]
OH hold on I’m sorry I didn’t see what you were doing

So the Phoenix Ring / Solar Emblem is an item that *grants you the ability to **shoot** fireballs,* you need to click the keybind (H by default) to shoot them (does not require fire charges, though that’s an interesting idea)

**Comment by davros364** [comment]
Thx so much i was wondering what happened to the pheonix ring once i updated and i got the acheivement! great job and love the ather!
