### ISSUE TITLE
[Bug]: Aether Redux stop playing song from True Ending Mod

### ISSUE THREAD

**Issue by SimulationOfMario** [Zepalesque/Aether-Redux-Issue-Tracker#121]
### Minecraft Version

1.20.1

### Mod Version

2.0.15

### Forge/Neoforge Version

47.2.0

### What happened?

The Ender Dragon battle song does not play (True Ending Mod), this is what appears on the console (log output part).

### What was the expected result?

The song should play correctly and nothing plays...

### Steps to Reproduce

Download True Ending + Aether redux (and dependencies), enter the End, once near the Dragon the song should play

### Log Output (if applicable)

[16:27:54] [Render thread/INFO] [ne.ze.re.Redux/]: Caught potential overlapping music track attempting to play in the Aether! Sound ID: true_ending:music.dragon
[16:27:54] [Render thread/INFO] [ne.ze.re.Redux/]: If this was logged halfway through the music track playing and cancelled it, this is an issue, please report it to the Aether: Redux's issue tracker.

### Is this a compatibility issue with another mod?

True Ending: Ender Dragon Overhaul

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
odd, I will look into it

**Comment by SimulationOfMario** [comment]
Thank You, I have found that in version 2.0.11 of Redux the problem does not occur (2.0.12 and above yes).

**Comment by Zepalesque** [comment]
ah I figured out the issue, this will be fixed in 2.0.16

**Comment by SimulationOfMario** [comment]
Ty!  
2.0.16 will be available in 1.20.1, right?

**Comment by Zepalesque** [comment]
yep! All of 2.0’s subversions will support it, I don’t plan to drop 1.20.1 support until version 2.1, which will be on 1.20.4 or later

**Comment by Zepalesque** [comment]
fixed as of 2.0.16
