### ISSUE TITLE
Blight bunny spawner and Cockatrice spawner entity causes a crash if attempted to be rendered in JER mob drops

### ISSUE THREAD

**Issue by NoalSimon** [Zepalesque/Aether-Redux-Issue-Tracker#124]
### Minecraft Version

1.19.2

### Mod Version

2.0.15

### Forge/Neoforge Version

43.3.5

### What happened?

If you open the full compendium of mob drops with just enough resources and attempt to scroll through it, the game will crash upon attempting to load the entry for the cockatrice spawner or the blight bunny spawner. I am attempting to blacklist the entry in JER config, but there is no instruction on how to work it. 

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-06-08 18:18:46
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.entity.EntityRenderer.m_7860_(net.minecraft.world.entity.Entity, float)" because "entityrenderer" is null

Details:
	Entity Type: aether_redux:blightbunny_spawner (net.zepalesque.redux.entity.util.EntitySpawner)
	Entity ID: 338
	Entity Name: Blightbunny Spawner
	Entity's Exact location: 0.00, 0.00, 0.00
	Entity's Block location: World: (0,0,0), Section: (at 0,0,0 in 0,0,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null

### What was the expected result?

That the game wouldn't crash when someone scrolls through mob drops

### Steps to Reproduce

Open Just enough resources mob drop tab by clicking on the main tab when looking at any mobs compendium of drops in their ui. then scroll until you hit the two problem entities and your game will crash.

### Crash Report (if applicable)

[crash-2024-06-08_18.18.46-client.txt](https://github.com/user-attachments/files/15753942/crash-2024-06-08_18.18.46-client.txt)

### Is this a compatibility issue with another mod?

Just Enough Resources

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it only occurs *with* Redux installed, and not without
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
These are internal mobs, and are used for spawning. They are not meant to work as actual mobs, and do not have renderers. I don't know if there's a way to disable certain mobs or not for JER but if there is then that may work.

**Comment by Zepalesque** [comment]
on second thought, I should probably do that on my end

**Comment by NoalSimon** [comment]
there is no way to disable singular entities in JER, you can only blacklist entire tabs. EMI doesn't attempt to render the mob as it only checks mobs with an actual drop table, so I have been using that. regardless it's a pretty brutal bug.

**Comment by Zepalesque** [comment]
ah, I see
Data generation of loot tables usually uses set lists of objects that *must* have loot generated for them, and in the case of entity loot, this includes all mobs that aren't in the entity category `MobCategory.MISC`.
The spawners intentionally don't use this, as to allow them to spawn in the world.
Because of this, I gave them an empty loot table
I can probably manually exclude them though, that should hopefully fix the issue
I'll also give them an empty entity renderer as based on the crash it seems that is at least a *part* of the issue

**Comment by Zepalesque** [comment]
should be fixed as of v2.0.16c
