### ISSUE TITLE
[Bug]: Can't launch with Protect Your Moa

### ISSUE THREAD

**Issue by QianFuv** [Zepalesque/Aether-Redux-Issue-Tracker#125]
### Minecraft Version

1.19.2

### Mod Version

2.0.16b

### Forge/Neoforge Version

43.3.13

### What happened?

Can't launch with Protect Your Moa.

### What was the expected result?

Launch normally with Protect Your Moa mod.

### Steps to Reproduce

Just install The-Aether-Redux and Protect Your Moa.

### Log Output (if applicable)

https://mclo.gs/Eorv86K

### Crash Report (if applicable)

https://mclo.gs/hnS6w32

### Is this a compatibility issue with another mod?

Protect Your Moa

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it only occurs *with* Redux installed, and not without
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
fixed in v2.0.16c
