### ISSUE TITLE
Bug [1.19.2] Holystone Furnace doesn't have an ui

### ISSUE THREAD

**Issue by meowkitty9694e** [Zepalesque/Aether-Redux-Issue-Tracker#13]
Forge 1.19,2 Version 1.0.5

Right Clicking a holystone furnace does nothing

1. Place a holystone furnace
2. Right click it
3. No UI

It should open a ui where you can smelt stuff.

**Comment by Zepalesque** [comment]
Fixed in 1.1-1.19.2
