### ISSUE TITLE
[Bug]: Wynd Bagel/Blueberry Bagel Hunger/Saturation Values appear to be incorrect or switched

### ISSUE THREAD

**Issue by Chaotic-Firewolf** [Zepalesque/Aether-Redux-Issue-Tracker#130]
### Minecraft Version

1.20.1

### Mod Version

2.0.16c

### Forge/Neoforge Version

neoForge 47.1.106

### What happened?

Wynd Bagel provides 6 Hunger Points (3 Hunger icons)

Blueberry Bagel provides 3 Hunger Points (1.5 Hunger icons)

### What was the expected result?

The Blueberry Bagel, which requires one additional item to craft, should have a higher Hunger value than the Wynd Bagel.

### Steps to Reproduce

Run the game with both Aether Redux and Appleskin installed, hover over both items with your mouse.

### Additional Context/Information

![Screenshot 2024-06-29 143845](https://github.com/Zepalesque/The-Aether-Redux/assets/119152783/71a12ef6-a543-49f0-984b-e4e2b3dfc648)
![Screenshot 2024-06-29 143922](https://github.com/Zepalesque/The-Aether-Redux/assets/119152783/254759df-4c38-4b56-a7e0-0ba991efb087)

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it only occurs *with* Redux installed, and not without
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
the blueberry bagel gives a haste effect, which was why I made it give less hunger, but yeah I can make them a bit closer

**Comment by Zepalesque** [comment]
should be better now
