### ISSUE TITLE
[Bug]: Server doesnt load when using 2.0.17 instead of 2.0.16c

### ISSUE THREAD

**Issue by itsWarHammer** [Zepalesque/Aether-Redux-Issue-Tracker#133]
### Minecraft Version

1.20.1

### Mod Version

2.0.17

### Forge/Neoforge Version

47.3.1

### What happened?

I'm using the BetterMinecraft4 modpack, they told me to update from 2.0.16c to 2.0.17, and the server stopped loading, I have the latest versions of The Aether TerraBlender Aeroblender and Geckolib for 1.20.1

### What was the expected result?

Correct loading of the server

### Steps to Reproduce

Update from 2.0.16c to 2.0.17 on BMC4 Modpack

### Log Output (if applicable)

https://mclo.gs/TzAsK1a

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it only occurs *with* Redux installed, and not without
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
this is a Delightful issue, and has been fixed in their latest update
