### ISSUE TITLE
Bug [1.19.2]: server crash with Redux v1.1

### ISSUE THREAD

**Issue by Nycto97** [Zepalesque/Aether-Redux-Issue-Tracker#14]
**What version of the mod, Forge/Neoforge and Minecraft are you using?**
Forge 1.19.2 | 43.3.2

**Describe the bug**
Server crashes after updating mod to version 1.1

**To Reproduce**
1. Launch server with Redux v1.1 installed, along with the other mods I have installed (see crash report for mod list)
2. See server crash with message: The Aether: Redux (aether_redux) has failed to load correctly
§7java.lang.ExceptionInInitializerError: null

**Expected behavior**
Server starts up without problems while having Redux v1.1 installed, just like it did with Redux v1.0.5.

**Crash report (if necessary and/or applicable)**
https://pastebin.com/fX8QqaKc

**Log file (should be titled latest.log, if applicable)**
https://pastebin.com/cXYgZ4GW

**Additional context**
Worked fine on v1.0.5, crash only occurs after updating to v1.1

**Comment by Nycto97** [comment]
Extra info: client (same Forge version) launches just fine, no crashes on client

**Comment by HerrBeef** [comment]
happens also in 1.20.1 with forge 47.2.1.
the mod wants to load a client gui, (java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/components/AbstractWidget for invalid dist DEDICATED_SERVER)

**Comment by Zepalesque** [comment]
this will be fixed in v1.1.1, which should come out *relatively* soon
luckily it wasn't a super hard bug to fix, just some client code being accidentally loaded on the server

**Comment by Zepalesque** [comment]
fixed, in version 1.2!
