### ISSUE TITLE
[Bug]: No recipe for Sporing Blightwillow Wood

### ISSUE THREAD

**Issue by VoidLeech** [Zepalesque/Aether-Redux-Issue-Tracker#144]
### Minecraft Version

1.20.1

### Mod Version

2.0.17

### Forge/Neoforge Version

47.3.0

### What happened?

Attempted to craft Sporing Blightwillow Wood using the standard 4 logs->3 wood recipe, but that doesn't work for Sporing Blightwillow.

### What was the expected result?

Sporing Blightwillow Wood is craftable.

### Steps to Reproduce

1. Load world
2. Check recipes for Sporing Blightwillow Wood (there are none)

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it only occurs *with* Redux installed, and not without
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
fixed in 2.0.18
