### ISSUE TITLE
[Change Request]: Remove Blightwillow Log walls

### ISSUE THREAD

**Issue by Qwerty97475** [Zepalesque/Aether-Redux-Issue-Tracker#150]
### What would you like to see changed?

While they do look kinda cool, no other mod (that I know of) or vanilla tree uses walls in their trees, neither does Aether Redux have any other trees with this. For consistency reasons, either every wood type should have a wall for their (stripped) logs, which would be quite hard, or the blightwillow log walls should be removed from the game.
I think the trees would probably look alright without the walls tbh

There aren't even plank walls either

Alternatively, could they be reimplemented as a similar block that isn't just a reskinned wall?

### Why do you think this change should be made?

Consistency reasons across mods
I don't like searching up "log" on JEI and then finding 1 wall amongst a bunch of full blocks
It doesn't really make sense

### Please also confirm the following before submitting the request:

- [X] This suggestion is not a duplicate
- [X] This suggestion does not change the general feel of the mod too much

**Comment by Zepalesque** [comment]
These exist as compat with the [Aether: Genesis](https://github.com/The-Aether-Team/The-Aether-Genesis) addon, and all wood types have log walls when it is installed.
