### ISSUE TITLE
[Feature Request]: What does the yellow shimmer cow say

### ISSUE THREAD

**Issue by AzureMH** [Zepalesque/Aether-Redux-Issue-Tracker#151]
### What is your request?

So i found this wierd creature and i killed one of them.
l can recognize it said 'no' and 'why do you do this' when hit and died.
Tried looking into the assets of the mod and what i got is 'vwakazoom'.
So what does vwakazoom mean?

### Why do you think the feature should be added?

I want to know

### Please also confirm the following before submitting the request:

- [X] This suggestion is not a duplicate
- [X] This suggestion fits nicely with the rest of the mod

**Comment by Zepalesque** [comment]
lmao you found the easter egg
it’s a direct reference to this lol:
https://www.youtube.com/watch?v=KILFYFhbr5M
