### ISSUE TITLE
Bug [1.20.1]: Missing model for the variant 'aether_redux:potted_enchanted_shrub#'

### ISSUE THREAD

**Issue by Xyphenore** [Zepalesque/Aether-Redux-Issue-Tracker#16]
**What version of the mod, Forge/Neoforge and Minecraft are you using?**

Minecraft: 1.20.1
Forge: 47.2.1
Aether: 1.0.0 Beta 1.3
Aather Redux: 1.2
Aero Blender: 1.0.1
Terra Blender: 3.0.0.169

**Describe the bug**

The game not crash.

I got a warning on the console:
Exception loading blockstate definition: 'aether_redux:blockstates/potted_enchanted_shrub.json' missing model for variant: 'aether_redux:potted_enchanted_shrub#'

**To Reproduce**

1. Install the mod.
2. Run the game with the console.
3. The warning is printed on the console during the game load.

**Expected behavior**

The warning must not be printed.

**Comment by Zepalesque** [comment]
yeah, I think I forgot to add a model for the potted enchanted shrub, which isn’t the end of the world since they’re inaccessible anyway and will likely be removed in the near future

The log warning has no effcts luckily, you should still be able to play the mod fine without any issues
