### ISSUE TITLE
Bug [1.20.1]: Couldn't load many tags, recipe and advancement if Aether genesis is missing.

### ISSUE THREAD

**Issue by Xyphenore** [Zepalesque/Aether-Redux-Issue-Tracker#17]
**What version of the mod, Forge/Neoforge and Minecraft are you using?**

Minecraft: 1.20.1
Forge: 47.2.1
Aether: 1.0.0 Beta 1.3
Aether Redux: 1.2
Aero Blender: 1.0.1
Terra Blender: 3.0.0.169

**Describe the bug**

I got errors on the console:

Couldn't load tag [aether_genesis:blue_swet_jelly (from aether-redux-1.2-1.20.1-neoforge.jar), aether_genesis:golden_swet_jelly (from aether-redux-1.2-1.20.1-neoforge.jar), aether_genesis:dark_swet_jelly (from aether-redux-1.2-1.20.1-neoforge.jar)] as it is missing following references: aether_genesis:blue_swet_jelly (from aether-redux-1.2-1.20.1-neoforge.jar), 
	aether_genesis:golden_swet_jelly (from aether-redux-1.2-1.20.1-neoforge.jar), 
	aether_genesis:dark_swet_jelly (from aether-redux-1.2-1.20.1-neoforge.jar)

Parsing error loading recipe aether_redux:genesis_dark_gummy_swet
com.google.gson.JsonSyntaxException: Unknown item 'aether_genesis:dark_swet_ball'

Parsing error loading custom advancement aether_redux:recipes/genesis_dark_gummy_swet: Unknown item id 'aether_genesis:dark_swet_ball'

I got warnings too:

Unable to decode loot conditions
com.google.gson.JsonSyntaxException: Unknown entity type 'aether_genesis:dark_swet'

Could not decode GlobalLootModifier with json id aether_redux:genesis_dark_swet_ball_increase - error: Unknown entity type 'aether_genesis:dark_swet'

The game not crash.

**To Reproduce**

1. Install the mod
2. Run the game with the console
3. After loading the game, go to world creation window

**Expected behavior**

No error if the optional dependency 'aether_genesis' is missing.

**Comment by Zepalesque** [comment]
This is due to these tags/recipes/advancements and stuff being compatibliity features with the genesis addon
unfortunately, there isn’t really a way that I know of to prevent the log warnings without rewriting a bunch of my code that generates jsons, but I can look into doing that sometime in the future
