### ISSUE TITLE
Bug [1.20.1]: Couldn't load element loot_table aether_redux:blocks/sprouting_lightroots

### ISSUE THREAD

**Issue by Xyphenore** [Zepalesque/Aether-Redux-Issue-Tracker#18]
**What version of the mod, Forge/Neoforge and Minecraft are you using?**

Minecraft: 1.20.1
Forge: 47.2.1
Aether: 1.0.0 Beta 1.3
Aether Redux: 1.2
Aero Blender: 1.0.1
Terra Blender: 3.0.0.169

**Describe the bug**

The game not crash.

I got this error on the console:
Couldn't parse element loot_tables:aether_redux:blocks/sprouting_lightroots
com.google.gson.JsonSyntaxException: Block Block{aether_redux:sprouting_lightroots} has no property half

**To Reproduce**

1. Install the mod
2. Run the game with the console
3. After loading the game, go to world creation window

**Expected behavior**

No error.

**Comment by Zepalesque** [comment]
ah, this seems to be a leftover from when sprouting lightroots were double plant blocks, I’ll fix this in the next update

**Comment by Zepalesque** [comment]
This is now fixed, in v1.3
