### ISSUE TITLE
Bug [1.20.1]: Parsing error for some loading recipes if missing Deep Aether

### ISSUE THREAD

**Issue by Xyphenore** [Zepalesque/Aether-Redux-Issue-Tracker#19]
**What version of the mod, Forge/Neoforge and Minecraft are you using?**

Minecraft: 1.20.1
Forge: 47.2.1
Aether: 1.0.0 Beta 1.3
Aether Redux: 1.2
Aero Blender: 1.0.1
Terra Blender: 3.0.0.169

**Describe the bug**

The game not crash.

But I got errors on the console:

Parsing error loading recipe aether_redux:spore_blight_deep_aether_aether_moss_carpet_to_blightmoss_carpet
com.google.gson.JsonSyntaxException: Invalid block: deep_aether:aether_moss_carpet

Parsing error loading recipe aether_redux:spore_blight_deep_aether_aether_moss_block_to_blightmoss_block
com.google.gson.JsonSyntaxException: Invalid block: deep_aether:aether_moss_block

**To Reproduce**

1. Install the mod
2. Run the game with the console
3. After loading the game, go to world creation window

**Expected behavior**

It seem the mod had the optional dependency 'deep_aether'
No error if the dependency is missing.

**Comment by Zepalesque** [comment]
Similarly to #17 , this is due to these recipes being for compatibility with Deep Aether
I can look into an altermative way to generate compatibility data files at some point which should get rid of the log warnings, but luckily there shouldn’t be any effect on gameplay
