### ISSUE TITLE
Bug [Forge 1.19.2]: Prismatic Petals Model Missing

### ISSUE THREAD

**Issue by Lucipo** [Zepalesque/Aether-Redux-Issue-Tracker#20]
**What version of the mod, Forge/Neoforge and Minecraft are you using?**
aether-redux-1.2-1.19.2-forge

**Describe the bug**
Models for petals do not render in-world

**To Reproduce**
1. Go to aether
2. Take a stroll and look around
3. Biomes with any kind of prismatic petal have no model

**Expected behavior**
It shouldnt be a missing cs:source block :3

**Screenshots**
![image](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/assets/36358294/6f930fa9-46db-4792-beeb-366a823051e5)

**Log file (should be titled latest.log, if applicable)**
[latest.log](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/12908622/latest.log)

**Additional context**
I turned off all resource packs and the issue persists.

**Comment by Zepalesque** [comment]
Hmm, uh oh, I’ll fix this in the next update

**Comment by Zepalesque** [comment]
> It shouldnt be a missing cs:source block :3

lol

**Comment by Zepalesque** [comment]
Ok, this is now fixed in v1.3!
