### ISSUE TITLE
Bug 1.19.2: Large Biome World Gen Crashes

### ISSUE THREAD

**Issue by SHXRKIIE** [Zepalesque/Aether-Redux-Issue-Tracker#22]
**What version of the mod, Forge/Neoforge and Minecraft are you using?**
FORGE 43.3.2 aether-redux-1.2-1.19.2-forge.jar

**Describe the bug**
Choosing large world gen crashes

**To Reproduce**
1. Add Aether and Aether Redux (I am using SteamPunk Modpack)
2. Load game
3. Make world with Large Biomes
4. Crash

**Expected behavior**
Not to Crash

**Crash report (if necessary and/or applicable)**
[crash-2023-10-28_21.33.01-server.txt](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/13195938/crash-2023-10-28_21.33.01-server.txt)

**Log file (should be titled latest.log, if applicable)**
[2023-10-28-1.log](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/13195939/2023-10-28-1.log)

**Additional context**
Using SteamPunk Modpack (Shouldnt really make a difference?

**Comment by Zepalesque** [comment]
hmm, maybe large biomes have different behavior for how it creates the world, I’ll look into this

**Comment by Zepalesque** [comment]
This should be fixed now as of v1.3!
