### ISSUE TITLE
Bug [1.19.2]: Crash to desktop on Moa's rendering

### ISSUE THREAD

**Issue by LifusChrustus** [Zepalesque/Aether-Redux-Issue-Tracker#23]
**What version of the mod, Forge/Neoforge and Minecraft are you using?**
- Aether-redux-1.2
- MC 1.19.2
- Forge 43.2.21

**Describe the bug**
While traveling across the Aether islands I get random crashes when meeting Moas (well... while not actually even seeing them at all).

**To Reproduce**
1. Go to Aether dimension
2. Travers in it for some time
3. Wait for Moa to appear somewhere 
4. Crash to desktop

**Expected behavior**
The game shouldn't crash on Moa spawning/rendering

**Screenshots**
--------------

**Crash report (if necessary and/or applicable)**
ex: https://pastebin.com/biLdzVFQ

**Log file (should be titled latest.log, if applicable)**
ex: https://pastebin.com/egnkBmJK   (Not a whole file due to it being too large. Only the last part)

**Additional context**
I do use a ton of other different mods, including performance optimizing mods such as rubidium...

Error message from the launcher:
The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot invoke "com.aetherteam.aether.api.registers.MoaType.getMoaTexture()" because the return value of "com.aetherteam.aether.entity.passive.Moa.getMoaType()" is null

**Comment by Zepalesque** [comment]
hmm, odd, luckily I have an idea of how to fix it, although can I have your mod list so I can reproduce the issue and debug the actual behavior of the moa?

**Comment by LifusChrustus** [comment]
The modlist itself is a modpack called Triforge II v1.3 and some additional mods.
Here's a list of those that I've added myself:
- Aether: Redux 1.2
- Aeroblender 1.0
- TerraBlender 2.0.1
- Deep Aether 1.0.0
- Enigmatic Legacy 2.26.5
- Iron's RPG Elements 1.1.1
- Citadel 2.1.4
- Alex's mobs 1.21.1
- Aquamirae 6.API15
- Archbows 1.1.8
- Ars nouveau 3.20.0
- Blue Skies 1.3.20
- Born in chaos 1.7
- Createarmory 0.6
- Deeper caves 1.2.0
- Ender Space 1.0.1
- genshininstrument 3.3.1
- Gnumus settlement 1.7
- goblintraders 1.8.0
- guard villagers 1.5.8
- hourglass 1.2.1.1
- library ferret 4.0.0
- natures compass 1.10.0
- nethers delight 3.1
- random crits 1.0.3
- realm rpg fallen adventurers 1.0.1
- recall 1.3.1
- sortilege 1.2
- structure gel 1.4.6
- trade cycling 1.0.5
- twilight forest 4.2.1518
- warrior rage 1.2.2

**Comment by Zepalesque** [comment]
Ah thanks, yeah I think I know the issue now, this will be fixed in the next update!

**Comment by LifusChrustus** [comment]
Good to hear it! Thanks for your fast response ;)

**Comment by Zepalesque** [comment]
Ok, fixed in v1.3!
