### ISSUE TITLE
Bug: Cockatrice rib recipe overrides vanilla arrow recipe

### ISSUE THREAD

**Issue by Zepalesque** [Zepalesque/Aether-Redux-Issue-Tracker#24]
**What version of the mod, Forge/Neoforge and Minecraft are you using?**
N/A, assumedly affects all versions

**Describe the bug**
When redux is installed, the arrow recipe is *completely* overriden by the cockatrice rib arrow recipe

**To Reproduce**
1. Install the mod
2. Attempt to craft an arrow with flint, only for it to fail
3. Attempt to craft an arrow with a cockatrice rib, to see it succeed

**Expected behavior**
Both recipes should work.

**Screenshots**
N/A

**Crash report (if necessary and/or applicable)**
N/A

**Log file (should be titled latest.log, if applicable)**
N/A

**Additional context**
Taken from curseforge comments, as seen here:
![IMG_2775](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/assets/60141811/7513e048-f897-4dac-8daa-8a8fb8c6e203)

**Comment by What-The-Cheick** [comment]
Can confirm after testing that this mod specifically is causing it, and checking the recipe with JEI/EMI, the vanilla recipe is absent

**Comment by Zepalesque** [comment]
Fixed, in v1.3
