### ISSUE TITLE
Cloudcap Jungle and Blight biomes not generating properly

### ISSUE THREAD

**Issue by xaphlactus** [Zepalesque/Aether-Redux-Issue-Tracker#25]
- Forge 47.2.0, Minecraft 1.20.1 -

[latest.log](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/13223852/latest.log)
Sizable modlist, but the important ones in this case are the 1.20.1 Aether addon suite (The Aether, Aeroblender+Terrablender, Ancient Aether, Lost Aether Content, Deep Aether, and obv Aether: Redux) - all mods are as up-to-date as I can access as of 10/31.

Cloudcap Jungle simply does not generate - and when it does, its just in the void with no land and only in one small spot of air, nowhere else (went 15000 blocks out and it just couldn't find it). The Blight at least gets a couple dozen blocks on the bottom end of islands for a pitiful mini-biome, but still is not generating as a true biome.
I have disabled Ancient Aether generation changes in the config so it's vanilla generation, plus altered the height parameters of the 2 biomes in the A:R config and even turned off depth density entirely just to see if they would appear as normal biomes - see result above. (With Ancient Aether generation, the biomes both refuse to exist anywhere but where land specifically does not generate.)

I wanted to see the cloudcap jungle (especially seeing the latest changelog changing some things with it) but I have yet to have ever seen it :(

**Comment by Zepalesque** [comment]
I believe there are some issues with compatibility (especially worldgen/biome-related stuff) with ancient aether right now, I’ll try to look into it at some point

**Comment by Aerioos** [comment]
This is happening to me as well, I do not have Ancient Aether installed. Only Aether related mods are
- [The Aether](https://modrinth.com/mod/deep-aether)
- [Deep Aether ](https://modrinth.com/mod/deep-aether)
- [The Aether : Redux ](https://modrinth.com/mod/the-aether-redux)
- [Aeroblender ](https://modrinth.com/mod/aeroblender)

**Comment by Zepalesque** [comment]
@Aerioos hmm, can I see your log file? There’s a semi-recent change I did to fix a crash, that prints to the log when an error occurs, and I have a hunch that may be a portion of your issue (likely not the original though as iirc this issue was opened *before* I made that change)

**Comment by xaphlactus** [comment]
yeah my report was on A:R 1.3 and I just now tested the new 1.3.1 and I'm getting similar results - although somehow (on a first pass at least) it flipped the behavior, now The Blight is generating without terrain and Cloudcap Jungle is getting a mini biome lol

New log just in case (sorry still extensive modlist, I'm also trying to configure Alex's Caves spawning and all that, I can do just bare minimum testing eventually if absolutely necessary)
[latest.log](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/13301491/latest.log)

**Comment by Zepalesque** [comment]
hmm, considering that one of the biomes already spawns, I think this might just be a bug with how biomes spawn that isn’t really easily fixable, since because the aether is made of islands, biomes will sometimes spawn in areas that have no land, this is spmething I’ve fairly commonly run into while testing

**Comment by Zepalesque** [comment]
actually, you know what, I’ll reopen this, I have a potential idea for a fix
If I make the blight and cloudcap biomes *larger,* then they msy be more likely to actually intersect with an island

**Comment by xaphlactus** [comment]
one thing to note: the other biomes all generate fine, as well as other addon biomes too, its just those 2 that are incorrect.
is it possible they're forcing 3d biome placement and thus generating too low? I tried turning the "modify depth density" config off and i didnt notice any changes overall, but the 2 always are located lower than y40 (and thus in open air or mini-biome) so it could be that they need to be changed to be the same as all others for generating?

**Comment by Zepalesque** [comment]
okay so it turns out that this bug was just not happening in the dev environment for some reason, I ended up figuring out a way to fix it, so yeah this should be fixed as of v1.3.3
