### ISSUE TITLE
Bug [1.20.1]: Feature Placement crash

### ISSUE THREAD

**Issue by muon-rw** [Zepalesque/Aether-Redux-Issue-Tracker#28]
**What version of the mod, Forge/Neoforge and Minecraft are you using?**
Aether Redux 1.3
Minecraft 1.20.1
Forge 47.2.1

**Describe the bug**
Server crash upon specific feature placement (FieldsproutTreeFeature)

**To Reproduce**
1. Enter the Aether
2. Fly around for a bit

**Expected behavior**
Not crash

**Crash report (if necessary and/or applicable)**
https://mclo.gs/WAi34NO

**Additional context**
Using several other Aether addons, full mod-list is listed in the crash report.

**Comment by Zepalesque** [comment]
hmm uh oh, it seems I accidentially used the wrong `Lists` class 😂
yeah I’ll fix this in v1.4

**Comment by Zepalesque** [comment]
make that 1.3.1, fixed
