### ISSUE TITLE
Change Request: Refactor package name

### ISSUE THREAD

**Issue by muon-rw** [Zepalesque/Aether-Redux-Issue-Tracker#29]
**Please describe your request**
Change the package name to _literally anything that isn't just aether_

**Why do you think it should be done?**
In logs it is being confused by users with the main Aether mod. 
A recent example:
https://github.com/The-Aether-Team/The-Aether/issues/1837

**Do you have any specific ways of implementation in mind? (OPTIONAL)**
Maybe aetherredux

**Comment by Zepalesque** [comment]
hmm yeah seems like a good idea lol
the reason I originally had it like that was that its predecessor which I had made back in 2020 used that package name (so it was a little homage to that ~~despite me never even releasing that mod)~~ but yeah I can see how that would be confusing
Maybe I’ll do `net.zepalesque.redux` or something, I’ll have to think about that a bit, but yeah I can definitely do that

**Comment by Zepalesque** [comment]
done in v1.3.1
