### ISSUE TITLE
Bug [forge 47.1.3 1.20.1]: crash with modpack

### ISSUE THREAD

**Issue by Thunderrock424242** [Zepalesque/Aether-Redux-Issue-Tracker#30]
**What version of the mod, Forge/Neoforge and Minecraft are you using?**
Note that ‘latest’ is not a valid answer here, as the latest changes over time. Please type the actual versions. 1.3

**Describe the bug**
A clear and concise description of what the bug is. it crashes when i enable this mod

**To Reproduce**
1. Go to 'my modpack'
2. Click on 'downlaod and play if you need the exported pack let me know'

**Expected behavior**
it was supposed to load and world
**Screenshots**

**Crash report (if necessary and/or applicable)**
ex: [upload file here]

**Log file (should be titled latest.log, if applicable)**
ex: [upload file here] https://mclo.gs/atezaFH

**Additional context**
ex: it only seems to happen under [circumstances]

**Comment by Zepalesque** [comment]
already being tracker in #26, marking as duplicate
regardless of that, yeah this’ll be fixed in the next update

**Comment by Zepalesque** [comment]
fixed, in 1.3.1
