### ISSUE TITLE
Bug [1.19.2]: Mod won't start, tries to load config.

### ISSUE THREAD

**Issue by Kitteh6660** [Zepalesque/Aether-Redux-Issue-Tracker#31]
**What version of the mod, Forge/Neoforge and Minecraft are you using?**
Mod version 1.3.1 on Forge **43.3.2** for Minecraft **1.19.2**

**Describe the bug**
The mod crashes with the minimum number of mods.

**To Reproduce**
1. Install the mod alongside the dependencies.
2. Clear the config files.
3. Try to start Minecraft.

**Expected behavior**
Minecraft to start up and enter the main menu normally.

**Screenshots**
![image](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/assets/5838739/e1c66899-35eb-46f3-8d62-b516114892cb)

**Crash report (if necessary and/or applicable)**
[crash-2023-11-08_16.20.32-fml.txt](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/13301453/crash-2023-11-08_16.20.32-fml.txt)

**Log file (should be titled latest.log, if applicable)**
[latest.log](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/13301451/latest.log)

**Additional context**
Ran the bare minimum amount of mods needed and it still crashes.

**Comment by PhweeDev** [comment]
Same issue here

**Comment by togera13** [comment]
Here is my crashlog with modernfix's better logging thing if that helps. Me and my friends are going to roll back to the older version of Aether Redux for now.
[crash-2023-11-08_17.40.19-fml.txt](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/13301999/crash-2023-11-08_17.40.19-fml.txt)
The log if this somehow helps:
[latest.log](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/13302003/latest.log)

**Comment by Zepalesque** [comment]
it seems like I messed something up when splitting the gold cloud config into one for the block and one for the parachute, oops!
this will be fixed in v1.3.2

**Comment by Zepalesque** [comment]
oh right I forgot to close this
this should be fixed now
