### ISSUE TITLE
[Bug]: Water lakes don't generate in Aether Redux biomes

### ISSUE THREAD

**Issue by 0Navis0** [Zepalesque/Aether-Redux-Issue-Tracker#44]
### What would you like to see changed?

It looks like water lakes don't generate in Aether Redux biomes, while they do in Aether biomes.

### Please confirm the following:

- [X] This suggestion is not a duplicate
- [X] This suggestion does not change the general feel of the mod too much

**Comment by Zepalesque** [comment]
hmm, that’s odd, they *should* be, I’ll look into that

**Comment by Zepalesque** [comment]
Although another thing to note is that this fits a bit more as a bug report, since it’s unintended behavior

**Comment by 0Navis0** [comment]
Yeah I know, it's just that the issue model doesn't fit really well for issues which don't cause crashes. 

Anyway the issue might come from the Aether itself. Water lakes seem to generate pretty rarely in Aether biomes. I don't think it's normal. I created an issue about it on Aether github.
https://github.com/The-Aether-Team/The-Aether/issues/1948
