### ISSUE TITLE
[Change Request]: Deep Aether and Aether Redux both adds coarse aether dirt

### ISSUE THREAD

**Issue by 0Navis0** [Zepalesque/Aether-Redux-Issue-Tracker#45]
### What would you like to see changed?

Deep Aether and Aether Redux both adds coarse aether dirt. It would be great if you could agree which mod should add it for preventing content duplication.

### Please confirm the following:

- [X] This suggestion is not a duplicate
- [X] This suggestion does not change the general feel of the mod too much

**Comment by Zepalesque** [comment]
yeah, what I’ve thought of maybe doing is replacing my coarse dirt when deep aether is installed so that when they’re both installed there’s no duplication like that, but then redux will still have coarse dirt when it’s used without deep aether, so I’ll probably end up doing something like that

**Comment by Zepalesque** [comment]
done in version 2.0
