### ISSUE TITLE
[Bug]: Glacia Sign on Wisteria Chest

### ISSUE THREAD

**Issue by MeatFliez** [Zepalesque/Aether-Redux-Issue-Tracker#47]
### Minecraft Version

1.19.2

### Mod Version

1.20

### Forge/Neoforge Version

43.3.5

### What happened?

i placed a glacia wood sign in the aether on a wisteria chest and it totally crashes my game. 

### What was the expected result?

Sign would display the text regarding what was inside my chest like my other storage systems

### Steps to Reproduce

Go to aether with wisteria wood, craft wisteria chest (NOT the base Minecraft chest), place, craft glacia wood sign, crouch and place on chest face 

### Log Output (if applicable)

[crash-2024-01-10_00.43.05-client.txt](https://github.com/Zepalesque/The-Aether-Redux/files/13886156/crash-2024-01-10_00.43.05-client.txt)

### Additional Context/Information

Every time I start up my world my chunks don’t even load before it crashes completely again, so I can’t delete it. 

### Make sure to confirm these as well:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
hmm, odd, I’ll look into this for v2.0

**Comment by Zepalesque** [comment]
actually, this and #57 may be related, so hopefully when I re-port to 1.19.2 that should fix both of these

**Comment by Zepalesque** [comment]
hopefully should be fixed in 2.0.7 as I completely reported everything, if not then you can reopen this issue
