### ISSUE TITLE
[Bug]: Missing localizations

### ISSUE THREAD

**Issue by Brakeable980** [Zepalesque/Aether-Redux-Issue-Tracker#49]
### Minecraft Version

1.19.2

### Mod Version

1.3.4

### Forge/Neoforge Version

Forge 43.3.7

### What happened?

Just a small bug where some items and mobs such as Skyroot Chest Mimic are written as block.aether_redux.skyroot_chest_mimic when using jade and when it is in the inventory. 
Aether blocks item group in creative is also written as itemGroup.aether.blocks not sure if it's Aether problem or this mod.

### What was the expected result?

Items should be written as Sky Chest Mimic instead 

### Steps to Reproduce

There's no step needed to reproduce.

### Additional Context/Information

![17051480486791949801328136654416](https://github.com/Zepalesque/The-Aether-Redux/assets/156517359/02c04ba3-64f7-4f19-954a-7f31714941f4)
![17051480717573441598248434221088](https://github.com/Zepalesque/The-Aether-Redux/assets/156517359/8de46bca-daf7-4919-8ae4-6c4066f92c26)

### Make sure to confirm these as well:

- [X] The issue persists on the latest version of the mod.
- [x] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [x] This issue is not a duplicate of another issue
- [ ] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
Hmm, odd, I’ll fix this in v2.0

**Comment by Zepalesque** [comment]
Oh right, I forgot to mention before, the creative tab issue is an error with the base mod, so I suggest reporting it to their issue tracker
The update fixing the other bugs however should be released fairly soon

**Comment by Zepalesque** [comment]
fixed in 2.0.7
