### ISSUE TITLE
Bug: Incorrect location of the trapdoor

### ISSUE THREAD

**Issue by unroman** [Zepalesque/Aether-Redux-Issue-Tracker#5]
**Describe the bug**
One trapdoor isn't facing the correct direction

**To Reproduce**
1. Go to 'Slider Dungeon'
2. Click on 'Trapdors under him'
3. See error

**Screenshots**
![2023-06-04_22 49 34](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/assets/75941881/29fc6d9b-7489-4c5a-9f10-5034a059ab67)

**Comment by Zepalesque** [comment]
alright, I fixed the issue, this will be fixed in alpha.3
