### ISSUE TITLE
[Translation Updates]:  Some new translations for zh_ch.json of the 1.20.1-forge branch

### ISSUE THREAD

**Issue by LuminaHeinsborough** [Zepalesque/Aether-Redux-Issue-Tracker#50]
### What would you like to see changed?

"biome.aether_redux.cloudcap_jungle": "云际丛林",
"biome.aether_redux.frosted_forests": "寒霜森林",
"biome.aether_redux.gilded_groves": "镀金树林",
"biome.aether_redux.highfields": "高田",
"biome.aether_redux.the_blight": "枯潮",
"item_group.aether_redux.accessories": "天境：新生代—饰品",
"item_group.aether_redux.building_blocks": "天境：新生代—建筑方块",
"item_group.aether_redux.foods": "天境：新生代—食物",
"item_group.aether_redux.functional_blocks": "天境：新生代—功能方块",
"item_group.aether_redux.materials": "天境：新生代—原材料",
"item_group.aether_redux.misc": "天境：新生代—杂项",
"item_group.aether_redux.natural_blocks": "天境：新生代—自然方块",
"item_group.aether_redux.spawn_eggs": "天境：新生代—刷怪蛋",
"item_group.aether_redux.tools": "天境：新生代—工具",
"item_group.aether_redux.weapons": "天境：新生代—武器",
"key.aether_redux.category": "天境：新生代",

[https://github.com/LuminaHeinsborough/The-Aether-Redux/commit/9ccb7c209f774828b89eadb4fb9bca68e366b0cb](url)

### Why do you think this change should be made?

For compatibilities to the Nature's Compass mod and the Explorer's Compass mod.

### Please confirm the following:

- [X] This suggestion is not a duplicate
- [X] This suggestion does not change the general feel of the mod too much

**Comment by Zepalesque** [comment]
Sure, I can add these, although some of them will no longer exist/have different names in the next update so maybe once it is finished you could retranslate those

**Comment by LuminaHeinsborough** [comment]
My pleasure.

**Comment by Zepalesque** [comment]
ok, 2.0 is out, you could probably update this if you want at some point since the name changes and stuff are done
although I will note that the creative tab/item group translations are actually left over from back when the mod had its own tab instead of adding items to the aether’s tab, so those probably don’t need to be translated
