### ISSUE TITLE
[Veridium Tools]: Tools of Veridium Do not work with Ambrosia

### ISSUE THREAD

**Issue by OverwatchReaper** [Zepalesque/Aether-Redux-Issue-Tracker#52]
### Minecraft Version

1.20.1

### Mod Version

1.3.4

### Forge/Neoforge Version

NeoForge 1.20.1 47.1.79

### What happened?

The Veridium Set of tool do not work with Ambrosia they accept it but promptly disappear only spamming the book of lore fix's it or rejoining as the tool vanishes but by clicking on the slot it reappears unaltered by its ambrosia  as i don't like using githubs or am a tester but i only logged on here to report this as i think it's important to have atleast a look into fixing this and i never log into github unless it has irritated me to a large extent with playing a mod 

### What was the expected result?

The Ambrosia Infusing on the item making the counter go up

### Steps to Reproduce

go on any server you own or single player and just try and infuse your item of veritium with ambrosia

### Log Output (if applicable)

[00:47:04] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:04] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:04] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:04] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:04] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:04] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:04] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:04] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:04] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:04] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:04] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:04] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:04] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:04] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:04] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:04] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:04] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:04] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:11] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:04] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:04] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:11] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:11] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:11] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:11] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:11] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:11] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:11] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway
[00:47:11] [Render thread/WARN] [ne.ze.re.Redux/]:
 Attempting to get infusion level of non-veridium item! Reading NBT data anyway

### Additional Context/Information

![image](https://github.com/Zepalesque/The-Aether-Redux/assets/47681589/0e2a7201-17f9-418e-99cf-336fca80094d)
![image](https://github.com/Zepalesque/The-Aether-Redux/assets/47681589/f1754b42-3344-46a5-9900-e4b9bbaa889c)

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by OverwatchReaper** [comment]
i am not a Strong user of github so Parden if my "Intellect" on github chatter is almost non existent as i'm a hermit and hate Human beings but i like your mod so take that as a complement for a good person in a extent of my acceptance and tolerance

**Comment by Zepalesque** [comment]
don't worry lol
and yeah I've actually fixed this for the next version, so yeah once that releases, the bug should be fixed

**Comment by Zepalesque** [comment]
fixed in version 2.0
