### ISSUE TITLE
[Bug]: Moa model rendering with Ancient aether

### ISSUE THREAD

**Issue by RuafuMan-Obs** [Zepalesque/Aether-Redux-Issue-Tracker#58]
### Minecraft Version

1.20.1

### Mod Version

1.3.4

### Forge/Neoforge Version

forge-47.2.0

### What happened?

Seems all moa from Ancient aether doesn't render properly when moa model improvment turn on
![2024-02-05_23 22 46](https://github.com/Zepalesque/The-Aether-Redux/assets/33950546/7cb3bc81-ba50-49bf-9243-4ba4b781dace)

### What was the expected result?

Make compability with Ancient aether moas

### Steps to Reproduce

Every Ancient aether moa with moa model improvment turn on wont render properly

### Is this a compatibility issue with another mod?

Ancient aether

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
yeah i’m probably going to make textures for those sometime before the next update is done

**Comment by Zepalesque** [comment]
done in commit 5c969e8, will be in release 2.0

**Comment by Zepalesque** [comment]
fixed in version 2.0
