### ISSUE TITLE
Bug: Server startup crash 1.19.4

### ISSUE THREAD

**Issue by MrKashew** [Zepalesque/Aether-Redux-Issue-Tracker#6]
Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[crash-2023-06-17_01.09.42-fml.txt](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/11778322/crash-2023-06-17_01.09.42-fml.txt)

**Comment by MrKashew** [comment]
issue was aether was somehow missing from mods folder 🤦‍♂️

**Comment by Zepalesque** [comment]
Hmm, uh oh, I’ll try to fix this and upload alpha.3.5

**Comment by Zepalesque** [comment]
Fixed, in alpha.3.5!
