### ISSUE TITLE
[Bug]: crashes when Aether Redux is installed with Ancient Aether

### ISSUE THREAD

**Issue by Junnaturefox** [Zepalesque/Aether-Redux-Issue-Tracker#61]
### Minecraft Version

1.20.1

### Mod Version

1.3.4

### Forge/Neoforge Version

Forge 47.2.20

### What happened?

Same as the title

### What was the expected result?

Fix

### Steps to Reproduce

1. Install both Aether Redux and Ancient Aether mods.
2. Launch the game
3. Get a crash report

### Log Output (if applicable)

[https://mclo.gs/I1NEddt](https://mclo.gs/I1NEddt)

### Crash Report (if applicable)

[https://mclo.gs/ANSrpcv](https://mclo.gs/ANSrpcv)

### Is this a compatibility issue with another mod?

Ancient Aether

### Additional Context/Information

mod list:
![QQ截图20240219010501](https://github.com/Zepalesque/The-Aether-Redux/assets/104568909/5145fe9e-ad36-4794-9464-ba04d83656a7)
Both Aether Redux and Ancient Aether are excellent addons, please fix this, I really want to play them all together.

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Junnaturefox** [comment]
Builderdog841/Ancient-Aether#174

**Comment by Zepalesque** [comment]
known issue, will be fixed in v2.0
if you want a working version now though, I actually just released a pre-release for 2.0:
https://github.com/Zepalesque/The-Aether-Redux/releases/tag/2.0-pre2-1.20.1
note that there are some issues, such as the book of lore crashing the game

**Comment by Junnaturefox** [comment]
thx for fixing this
