### ISSUE TITLE
[Bug]: No hanging sign recipes

### ISSUE THREAD

**Issue by VoidLeech** [Zepalesque/Aether-Redux-Issue-Tracker#63]
### Minecraft Version

1.20.1

### Mod Version

2.0-pre10

### Forge/Neoforge Version

Forge 47.2.0

### What happened?

Tried to look up recipe of Aether Redux's hanging signs using JEI and noticed no recipe showing up.

### What was the expected result?

A recipe exists. 
These are currently not datagenned.

### Steps to Reproduce

Install JEI
Search for a hanging sign from Aether Redux
Click to view recipe (there is none)

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
Odd, I’ll look into it

**Comment by Zepalesque** [comment]
ah yeah it seems like I missed their recipes, this'll be fixed in the full release (since I don't *think* there will be any pre releases before the update releases)

**Comment by Zepalesque** [comment]
fixed in version 2.0
