### ISSUE TITLE
[Bug]: Cloudcap Stems don't connect with the cap blocks

### ISSUE THREAD

**Issue by VoidLeech** [Zepalesque/Aether-Redux-Issue-Tracker#64]
### Minecraft Version

1.20.1

### Mod Version

2.0-pre10

### Forge/Neoforge Version

Forge 47.2.0

### What happened?

I attempted to add full cloudcap (stems work by default) support to an auto-chopping feature and added cloud_cap_block to the appropriate tags.
Chopped the mushroom using the feature.
Cloud cap blocks remained.
Further investigation revealed there is a 1 block gap between the highest cloudcap stem and the cloud_cap_block.

### What was the expected result?

Cloudcap connects to its cap directly and not just via the spores.

### Steps to Reproduce

Either grow a cloudcap mushling or locate a naturally generated tall cloudcap
Break the top center cloudcap cap block
Observe air gap

### Additional Context/Information

![image](https://github.com/Zepalesque/The-Aether-Redux/assets/57987812/77a8fcb1-f722-49ff-88af-fc1262efadf1)
![image](https://github.com/Zepalesque/The-Aether-Redux/assets/57987812/67cee90d-15fe-4c85-8f63-83fc259d4a60)

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
uh oh lol
yeah I'll fix that

**Comment by Zepalesque** [comment]
excellent, that was very easy lol

**Comment by Zepalesque** [comment]
fixed in version 2.0
