### ISSUE TITLE
[Change Request]: Add a config option to disable the custom main menu

### ISSUE THREAD

**Issue by ianm1647** [Zepalesque/Aether-Redux-Issue-Tracker#65]
### What would you like to see changed?

as the title says, all i think is needed is a config option to disable the custom menu for people who don't want it

### Why do you think this change should be made?

having control over that would help a lot for modpack use and ease of access

### Please also confirm the following before submitting the request:

- [X] This suggestion is not a duplicate
- [X] This suggestion does not change the general feel of the mod too much

**Comment by Zepalesque** [comment]
This should already be possible, the menu uses the Cumulus API mod so you should be able to use it to switch back to the default

**Comment by Zepalesque** [comment]
oh actually, I just now realized, try disabling the first startup config in redux's config as well, this should prevent it from changing the menu on the first game load

**Comment by MokahTGS** [comment]
Which config controls the main menu???  This interferes with Fancy Menu modpacks like mine.  How do I turn off all of the added menu stuff from these mods??

**Comment by Zepalesque** [comment]
try having redux’s ‘first startup’ config disabled

**Comment by Zepalesque** [comment]
oh and then also maybe delete the cumulus mod’s config file so that it can switch to the correct main menu as well

**Comment by Zepalesque** [comment]
I can probably actually seperate the different configs for doing things on the first startup, so yeah this’ll be in v2.0.7

**Comment by Zepalesque** [comment]
added in 2.0.7

**Comment by Apocalyptichobo** [comment]
> added in 2.0.7

Can you explain where this is in the configs?

**Comment by Zepalesque** [comment]
It should be in the client config, under ‘Internal’ iirc
although you’ll still have to disable the menu api through cumulus’s config, redux’s config will only do it for new installs, such as modpack instances
