### ISSUE TITLE
[Bug]: knife veridium from aether delight mod causing crash

### ISSUE THREAD

**Issue by Marllon13** [Zepalesque/Aether-Redux-Issue-Tracker#66]
### Minecraft Version

1.20.1

### Mod Version

2.0

### Forge/Neoforge Version

43.2.3

### What happened?

knife veridium from aether delight mod causing crash and error in JEI, "Tooltip Error, see log".

### What was the expected result?

don't crash

### Steps to Reproduce

just hovering the cursor over the knife crashes, in the creative inventory.

### Log Output (if applicable)

[2024-03-07-5.log](https://github.com/Zepalesque/The-Aether-Redux/files/14519510/2024-03-07-5.log)

### Crash Report (if applicable)

[crash-2024-03-07_02.47.18-client.txt](https://github.com/Zepalesque/The-Aether-Redux/files/14519534/crash-2024-03-07_02.47.18-client.txt)

### Is this a compatibility issue with another mod?

aether delight

### Make sure to confirm these as well before submitting the report:

- [x] The issue persists on the latest version of the mod.
- [ ] All version numbers are properly recorded, no instances of ‘latest’
- [ ] All details are reported clearly and concisely
- [x] This issue is not a duplicate of another issue
- [x] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
This is likely something that'd have to be done on the devs of the Aether Delight's end, so I suggest reporting it to their issue tracker

**Comment by Zepalesque** [comment]
Although actually looking at the mod page, they don’t seem to have an issue tracker, so maybe comment on the curseforge page instead or something? not sure

**Comment by Marllon13** [comment]
I realized that I had a wrong conclusion, the mod that has this knife is actually Delightful. I saw that someone reported the same problem as mine and that the mod's creators are already aware.
