### ISSUE TITLE
[Bug]: Crashed on dedicated server

### ISSUE THREAD

**Issue by liangmoe** [Zepalesque/Aether-Redux-Issue-Tracker#67]
### Minecraft Version

1.20.1

### Mod Version

v2.0

### Forge/Neoforge Version

Neoforge 47.1.97

### What happened?

console freeze with crash report

### What was the expected result?

launch server without crash

### Steps to Reproduce

update redux from v1.3.4 to v2.0, launch server

### Log Output (if applicable)

https://mclo.gs/fVC5Xc8

### Crash Report (if applicable)

https://mclo.gs/gzFsWEC

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
Two things:
1: 2.0 has a ton of changes, and is not likely to work on a world previously using 1.3.4 (although if you completely regenerate the Aether it *may* work, not sure how to do that thought)
2: The server crash is still an issue unrelated to this, and I will look into it

**Comment by Zepalesque** [comment]
should be fixed in 2.0.1, still I suggest either creating a new world or regenerating the aether

**Comment by liangmoe** [comment]
Ok, thanks!
