### ISSUE TITLE
[Bug]: Crash with Mythic Metals w/ Connector

### ISSUE THREAD

**Issue by Starexify** [Zepalesque/Aether-Redux-Issue-Tracker#68]
### Minecraft Version

1.20.1

### Mod Version

2.0.1

### Forge/Neoforge Version

Forge 47.2.20

### What happened?

Crash with Mythic Metals and Connector??

### What was the expected result?

Not crash, the changelog states it was updated to fix crashes and it didnt.

### Steps to Reproduce

1. Install Aether Redux with Mythic metals through connector on forge.

### Log Output (if applicable)

[latest.log](https://github.com/Zepalesque/The-Aether-Redux/files/14527257/latest.log)

### Crash Report (if applicable)

https://pastebin.com/XUELhM3B

### Is this a compatibility issue with another mod?

Yes

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
I can’t seem to see what the issue with redux is, maybe try reporting it to the mythic metals issue tracker?

**Comment by Zepalesque** [comment]
also another thing I’ll note is that the update was specifically to fix a certain bug with the server crashing, so it won’t necessarily fix all server bugs

**Comment by Starexify** [comment]
> I can’t seem to see what the issue with redux is, maybe try reporting it to the mythic metals issue tracker?

I thought because whenever I add Aether Redux, it crashes. And it didnt do this before. only when updating aether redux

**Comment by Zepalesque** [comment]
Hmm, strange, in that case yeah I’ll look into it

**Comment by Starexify** [comment]
> Hmm, strange, in that case yeah I’ll look into it

I also reported to Mythic Metals the crash maybe finding a solution 👍

**Comment by Zepalesque** [comment]
Hmm, hold on, so does it work with 2.0 but not 2.0.1, or does it just not work with either?
Because if it’s just 2.0.1 then that’s *very* strange, because based on the crash I can’t see anything that relates to anything I changed in 2.0.1, odd

**Comment by Starexify** [comment]
> Hmm, hold on, so does it work with 2.0 but not 2.0.1, or does it just not work with either? Because if it’s just 2.0.1 then that’s _very_ strange, because based on the crash I can’t see anything that relates to anything I changed in 2.0.1, odd

It doesnt crash but the chests are all just empty

**Comment by Starexify** [comment]
And the latest.log : 
[latest.log](https://github.com/Zepalesque/The-Aether-Redux/files/14527736/latest.log)

**Comment by Starexify** [comment]
> Hmm, hold on, so does it work with 2.0 but not 2.0.1, or does it just not work with either? Because if it’s just 2.0.1 then that’s _very_ strange, because based on the crash I can’t see anything that relates to anything I changed in 2.0.1, odd

Mythic Metals author also replied if interested. Maybe useful
https://github.com/Noaaan/MythicMetals/issues/229

**Comment by Zepalesque** [comment]
seems to have been fixed on their side
