### ISSUE TITLE
[Bug]: Mod conflict (unknown mod) breaks JEI tooltips

### ISSUE THREAD

**Issue by katubug** [Zepalesque/Aether-Redux-Issue-Tracker#70]
### Minecraft Version

1.20.1

### Mod Version

2.0.2

### Forge/Neoforge Version

47.2.20

### What happened?

![2024-03-07_14 30 44](https://github.com/Zepalesque/The-Aether-Redux/assets/20935286/fca2dff7-0f4f-456c-87d1-b1b9cf802cfb)

All tooltips in JEI are broken. It says "see logs" but I couldn't find the part of the log which explained the issue. Reverting to 1.3.4 (the version I was on before I updated) fixes the issue.

### What was the expected result?

Tooltips should work.

### Steps to Reproduce

1. Launch modded instance
2. Open inventory
3. Hover over anything in JEI

### Log Output (if applicable)

https://gist.github.com/katubug/c9e8b76c634704598092c1766a7015a2

### Is this a compatibility issue with another mod?

yes, but unsure what mod

### Additional Context/Information

There are a bunch of errors in the log, but I'm not sure which are relevant. I did find that during testing, the only bit in the log that mentions "tooltips" is this:
```
[14:28:16] [main/WARN]: Error loading class: mezz/modnametooltip/TooltipEventHandler (java.lang.ClassNotFoundException: mezz.modnametooltip.TooltipEventHandler)
[14:28:16] [main/WARN]: Error loading class: me/shedaniel/rei/impl/client/ClientHelperImpl (java.lang.ClassNotFoundException: me.shedaniel.rei.impl.client.ClientHelperImpl)
```

But this appears even when I load up with tooltips working, so I don't think it's relevant.

About the conflict - I'm not sure what mod it's conflicting with. I have tried it in an isolated instance with just Aether Redux (and Aether and JEI obvs) and it doesn't occur. I also checked whether it was Legendary Tooltips or Better Tag Tips, but it's not. It's also not Supplementaries, Amendments, or Aquamirae. At this point I don't have the time to do a binary search, so I'm reporting with the hope that you see something in the logs that I don't - or that someone else has the same issue and can help narrow down where the conflict is.

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
Appears to be an issue with Delightful, I suggest reporting it to their issue tracker

**Comment by katubug** [comment]
Thank you so much, I will do! Can you tell me how you found that out, so that I can hopefully do it myself next time?

**Comment by Zepalesque** [comment]
Looking at the log, I saw that the class that caused the error was `net.brnbrd.delightful.common.item.knife.compat.aether_redux.VeridiumKnifeItem`, which points to it being a delightful issue
I looked at their repository, and it looked like this was fixed, so likely in the next update for the mod it should work properly

**Comment by brnbrd** [comment]
Yeah I will release the fix for Delightful shortly

**Comment by Zepalesque** [comment]
delightful fix is out, so I'll close this now
