### ISSUE TITLE
[Feature]: Cultists of the Sun (name unfinished)

### ISSUE THREAD

**Issue by Zepalesque** [Zepalesque/Aether-Redux-Issue-Tracker#78]
should resemble terraria’s lunar cultists
can be new mobs - would be better to mixin into the sun spirit’s method for spawning minions than modifying the existing minions

consider *not* adding this as well, ancient aether also had plans for a similar feature

**Comment by GreenForzeGaming** [comment]
make this a second phase of the sun spirit his bossfight is bleh like bounce back 3 ice balls too break his shield and then face his "cultist side that flies arouns makes copies of himself and shoots blaze balls

**Comment by Zepalesque** [comment]
> make this a second phase of the sun spirit his bossfight is bleh like bounce back 3 ice balls too break his shield and then face his "cultist side that flies arouns makes copies of himself and shoots blaze balls

I’d *prefer* to not change the bossfight itself *too* much, these will just be to replace the existing minions, but I’ll see what I can do

**Comment by Zepalesque** [comment]
closing this as I have decided to use checklists rather than individual issues for features like this
