### ISSUE TITLE
[Bug]: Crashes when trying to join the world

### ISSUE THREAD

**Issue by KerdoNepidor** [Zepalesque/Aether-Redux-Issue-Tracker#83]
### Minecraft Version

1.20.1

### Mod Version

2.0.5b

### Forge/Neoforge Version

47.2.20

### What happened?

Trying to create new world but in the end just crashing. Even if trying to join in already created world - crash

### What was the expected result?

An normal join world and gameplay? xd

### Steps to Reproduce

By... Just trying to play? xd

### Log Output (if applicable)

[latest.log](https://github.com/Zepalesque/The-Aether-Redux/files/14551885/latest.log)

### Crash Report (if applicable)

The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'byte net.zepalesque.redux.item.util.VeridiumItem.getCharge(net.minecraft.world.item.ItemStack)'

### Is this a compatibility issue with another mod?

idk

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
Try updating the Delightful mod, a crash with this mod was fixed in a recent version of the mod

**Comment by KerdoNepidor** [comment]
> Try updating the Delightful mod, a crash with this mod was fixed in a recent version of the mod

It works! Accept my gratitude!
