### ISSUE TITLE
[Question]: What to expect when updating from 1.3.4 to latest version (ex: 2.0.6)

### ISSUE THREAD

**Issue by elpocoburrito** [Zepalesque/Aether-Redux-Issue-Tracker#84]
### Minecraft Version

1.20.1

### Mod Version

1.3.4

### Forge/Neoforge Version

Forge 47.2.20

### What happened?

(Not a bug)
I was simply wondering what to expect if I was to forgo the warning of starting a new world and updating from 1.3.4 to 2.0.6, assuming I would delete the Aether dimension (but not the other dimensions and other saved content).

I'm assuming some items may have changed since, would the old ones just vanish? How would they break, if they do.

Thanks for your time and sorry if its not the right place to ask, I couldnt find any discord or other.

### What was the expected result?

N/A

### Steps to Reproduce

N/A

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
yeah, currently old items would vanish but I plan to fix that in the same way that minecraft remaps items from older versions at some point, maybe in 2.0.7
In fact I’ll keep this open to remind me lol
Once I implement it I’ll close this issue

**Comment by Zepalesque** [comment]
not *everything* will be perfect, since there are a few items that I reworked and moved their old abilities to new items, such as the sentry ring and enchanted ring, but hopefully for the most part once I implement it it’llbe possible to *mostly* continue in an existing world, ust with a new regenerated aether

**Comment by Zepalesque** [comment]
ok yeah once 2.0.7 is out updating worlds should be a much smoother process
in fact, apart from the renamed biomes being reset to `minecraft:plains` (which will be difficult to fix, but I may be able to figure it out at some point, perhaps for this update), you can even load existing worlds, and items/blocks should properly remap to their new counterparts
of course, they're missing a lot and have some broken things, but they *do* load
still suggest resetting the dimension once when updating from <1.3.4 to >2.0 though

**Comment by Zepalesque** [comment]
missing item stuff has been fixed in 2.0.7
