### ISSUE TITLE
[Bug]: Cloud Cap & Jellyshroom blocks dont break quicker when a hoe is used

### ISSUE THREAD

**Issue by CrystalZink** [Zepalesque/Aether-Redux-Issue-Tracker#85]
### Minecraft Version

1.20.1

### Mod Version

2.0.6

### Forge/Neoforge Version

47.2.20

### What happened?

Blocks such as Nether Wart & Warped Wart blocks break faster with Hoes.

This isn't the case with Cloud Cap & Jellyshroom Blocks & Cloudcap Spores, they still retain their default breaking speed.

### What was the expected result?

The blocks in question should break faster when a hoe of some kind is used.

### Steps to Reproduce

use a hoe of any kind on Jellyshroom or Cloud Cap blocks

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
fixed in 2.0.7
