### ISSUE TITLE
[Bug]: >>Moa and Cockatrice models render twice when playing The Aether: Redux alongside All Bark, All Bite<<

### ISSUE THREAD

**Issue by Minikemon** [Zepalesque/Aether-Redux-Issue-Tracker#87]
### Minecraft Version

1.20.1

### Mod Version

2.0.7

### Forge/Neoforge Version

47.1.3

### What happened?

The models for the Moa and Cockatrice mobs render twice with one of the models being smaller than the other when the mod All Bark, All Bite is installed. This only occurs when using the new models for the mobs in The Aether: Redux and not when they are disabled.

### What was the expected result?

The expected result is that the models only render once. 

### Steps to Reproduce

1. Install All Bark, All Bite and The Aether: Redux and all dependencies 
2. Ensure the configs are using the new models for the Moa and Cockatrice mobs
3. Load into a world and spawn Moa and Cockatrice
4. Observe that models render twice with one of the models being smaller than the other 

### Log Output (if applicable)

[latest.log](https://github.com/Zepalesque/The-Aether-Redux/files/14663188/latest.log)

### Is this a compatibility issue with another mod?

All Bark, All Bite

### Additional Context/Information

<img width="479" alt="duplicate" src="https://github.com/Zepalesque/The-Aether-Redux/assets/82803571/768ead1b-6d8e-4415-99ea-5a75ef89f0ce">
<img width="419" alt="duplicate2" src="https://github.com/Zepalesque/The-Aether-Redux/assets/82803571/56536040-771e-4627-9a36-3ef2c2312f7e">

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
oh heck right I still need to look into this

**Comment by Zepalesque** [comment]
fixed in 2.0.13
