### ISSUE TITLE
Bug [1.19.2]: AeroBlender Dependency Bug

### ISSUE THREAD

**Issue by JustVibin247** [Zepalesque/Aether-Redux-Issue-Tracker#9]
**What version of the mod, Forge/Neoforge and Minecraft are you using?**
Forge: 43.3.0 Minecraft: 1.19.2

**Describe the bug**
From the crash logs, it looks like it requires a higher version of AeroBlender than currently available for 1.19.2.

**To Reproduce**
1. Download Aether Redux & AeroBlender
2. See error

**Expected behavior**
For the game to launch.

**Crash log (if necessary and/or applicable)**
[latest.log](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/12707183/latest.log)

**Comment by Zepalesque** [comment]
hmm, you attached the log, could you also attach the crash report itself?

**Comment by Zepalesque** [comment]
Actually wait, this should be easy to fix, I think I know the issue

**Comment by Zepalesque** [comment]
fixed, in 1.0.3-1.19.2!

**Comment by Zepalesque** [comment]
oh
if there's still the bug, try using this release of terrablender, I may have misinterpreted the error:
[https://legacy.curseforge.com/minecraft/mc-mods/terrablender/files/4618490](url)

**Comment by Zepalesque** [comment]
okay it turns out that didn't fix it, however I figured it out and am about to fix it in an update

**Comment by Zepalesque** [comment]
forgot to close this lol
fixed in 1.0.4-1.19.2
