### ISSUE TITLE
[Bug]: loading crash

### ISSUE THREAD

**Issue by hyygybs** [Zepalesque/Aether-Redux-Issue-Tracker#90]
### Minecraft Version

1.19.2

### Mod Version

2.0.7c

### Forge/Neoforge Version

43.3.8

### What happened?

loading crash

### What was the expected result?

when i back to 1.3.4, it not crashed.

### Steps to Reproduce

[crash-2024-03-21_15.13.18-fml.txt](https://github.com/Zepalesque/The-Aether-Redux/files/14691612/crash-2024-03-21_15.13.18-fml.txt)

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
hmm, I only see one singular mention of redux here, but I can probably make a quick patch to remove an unfinished disabled-by-default feature that may be causing the problem

**Comment by Zepalesque** [comment]
should be fixed in 2.0.7d
