### ISSUE TITLE
[Bug]: >>portal sound<<

### ISSUE THREAD

**Issue by SGZ-Creations** [Zepalesque/Aether-Redux-Issue-Tracker#91]
### Minecraft Version

1.19.2

### Mod Version

2.0.7d

### Forge/Neoforge Version

43.3.2

### What happened?

Muting "aether:block.aether_portal.ambient": 0.0,
using ESM causes crashes shown in the logs

### What was the expected result?

Not to crash When near portal with sound muted

### Steps to Reproduce

Have Aether Redux and Extreme sound muffler mod. 
Mute the  "aether:block.aether_portal.ambient": 0.0,
be close to portal and when sound is triggered the crash should occur. 

### Crash Report (if applicable)

[crash-2024-03-22_22.31.03-client.txt](https://github.com/Zepalesque/The-Aether-Redux/files/14728758/crash-2024-03-22_22.31.03-client.txt)
[crash-2024-03-22_22.24.23-client.txt](https://github.com/Zepalesque/The-Aether-Redux/files/14728759/crash-2024-03-22_22.24.23-client.txt)
[crash-2024-03-22_22.15.58-client.txt](https://github.com/Zepalesque/The-Aether-Redux/files/14728760/crash-2024-03-22_22.15.58-client.txt)

### Is this a compatibility issue with another mod?

Extreme sound muffler

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
hmm, could I have the log file? I'm not seeing anything mentioning redux in the crash log

**Comment by Zepalesque** [comment]
oh hold on nevermind

**Comment by Zepalesque** [comment]
this appears to be an issue with the other mod, I suggest reporting to them to have them add a null check to make sure the SoundInstance is not null before setting the volume to 0

**Comment by Zepalesque** [comment]
right forgot about this
yeah so there isn’t a ton I can do for this, like I said before I suggest reporting it to their issue tracker if you haven’t already
