### ISSUE TITLE
[Bug]: >>Crash when entering Aether or Diminsions with Aether Blocks<<

### ISSUE THREAD

**Issue by KakashoLin** [Zepalesque/Aether-Redux-Issue-Tracker#92]
### Minecraft Version

1.20.1

### Mod Version

2.0.7d 

### Forge/Neoforge Version

47.2.0

### What happened?

Whenever you enter the Aether the game will crash to the desktop. Code references Aether:Redux. 

Some Snippets:
net.zepalesque.redux.client.ReduxColors.getAverageColor(ReduxColors.java:166) ~[aether-redux-2.0.7d-1.20.1-neoforge.jar%23616!/:2.0.7d] {re:classloading}
	at net.zepalesque.redux.client.ReduxColors.lambda$blockColors$1(ReduxColors.java:34) ~[aether-redux-2.0.7d-1.20.1-neoforge.jar%23616!/:2.0.7d] {re:classloading}

### What was the expected result?

Load into the Aether and move.

### Steps to Reproduce

Try to enter the Aether by any means or enter a dimension where Aether biomes may appear.

### Log Output (if applicable)

[AetherRedux2024-03-26-3.log](https://github.com/Zepalesque/The-Aether-Redux/files/14764191/AetherRedux2024-03-26-3.log)

### Crash Report (if applicable)

[AetherReduxcrash-2024-03-26_14.58.20-client.txt](https://github.com/Zepalesque/The-Aether-Redux/files/14764157/AetherReduxcrash-2024-03-26_14.58.20-client.txt)

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by KakashoLin** [comment]
Tested and the game runs normally and you are able to enter the Aether dimension if Aether:Redux is disabled. A similar issue occurs in a server environment. It will crash the player, and keep them locked in the dimension in a crash loop intill you manage to snag them out with a /tp command. Sometimes, the player crashes with the above issue will also take the server down.

**Comment by Zepalesque** [comment]
hmm, my first thought seeing the crash is maybe try embeddium instead of rubidium, since embeddium is specifically designed for mod compat, but yeah I’ll look into this

**Comment by Zepalesque** [comment]
I added a try/catch block to that portion of the code in 2.0.8, so *hopefully* it won’t *crash* anymore, still not sure exactly why it’s happening though
