### ISSUE TITLE
[Bug]: >>Can't turn the menu off<<

### ISSUE THREAD

**Issue by cutekitticat** [Zepalesque/Aether-Redux-Issue-Tracker#93]
### Minecraft Version

1.20.1

### Mod Version

2.0.7d

### Forge/Neoforge Version

47.2.21

### What happened?

I need to disable the Aether Redux menu, but the option is already disabled by default and so i can't remove the menu.
I tried to set it to true but nothing happens and the mod resets the option to false.

### What was the expected result?

I just need to be able to remove the menu.

### Steps to Reproduce

the option is already off so it's impossible to deactivate it.

### Log Output (if applicable)

#Internal value to do menu changes. Set this to false in modpacks if you want to use your own menu.
	"First Startup - Menu Setup" = false

### Additional Context/Information

![image_2024-03-29_025323132](https://github.com/Zepalesque/The-Aether-Redux/assets/141377921/b6683376-a5a6-47c8-8df1-875b5fcbb144)

![image_2024-03-29_025414684](https://github.com/Zepalesque/The-Aether-Redux/assets/141377921/abe3c041-fc0a-4a76-9871-e8e47dc4944f)

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
oh yeah sorry - the menu has to be disabled in the Cumulus mod’s config, the one there is just for whether or not redux should set the menu to its own _on the first startup_

**Comment by Zepalesque** [comment]
going to pin this for anyone in the future with this issue

**Comment by Zepalesque** [comment]
I should probably make the config wording a bit better to say that it doesn’t disable the menu as well, so I’ll reopen this to remind me

**Comment by cutekitticat** [comment]
OK Thank you !!
