### ISSUE TITLE
[Bug]: Skyroot pick should drop 2 for 1 for naturally generated stone (like frosted holystone)

### ISSUE THREAD

**Issue by Cardboard231** [Zepalesque/Aether-Redux-Issue-Tracker#94]
### Minecraft Version

1.20.1

### Mod Version

1.3.4

### Forge/Neoforge Version

47.2.17

### What happened?

Just as the title, the skyroot pickaxe should give 2 for 1 stops for [naturally generated stones](https://aether.fandom.com/wiki/Pickaxe?sh=YjD5RWWyWB__7973&m=1&utm_source=twitter&utm_campaign=h2s)

### What was the expected result?

getting 2 for 1 on frosted holystone

### Steps to Reproduce

mine it with a skywood pick

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
I suggest updating to version 2.0 or later (current latest is 2.0.7c), although I don't think I've fixed this yet so I'll do that in 2.0.8

**Comment by Zepalesque** [comment]
~~oh for heck’s sake~~ apparently i can’t mention an issue in a commit without github auto-closing it :joy: for clarification, this is not fixed as 2.0.8 is not released yet
will be *very* soon though

**Comment by Zepalesque** [comment]
Should now be fixed in 2.0.8
