### ISSUE TITLE
[BUG]: The game crashes when a mob kills me

### ISSUE THREAD

**Issue by Bruskych** [Zepalesque/Aether-Redux-Issue-Tracker#95]
### Minecraft Version

1.20.1

### Mod Version

UPDATE -Ω.001 !!

### Forge/Neoforge Version

Forge 47.2.19

### What happened?

I'm playing on my ModPack and decided to update the Aether Redux mod to the latest version (UPDATE -Ω.001 !!). After the update, if any mob kills me (no matter what, any mob at all), the game crashes and crashes! All other dependencies of this mod are also updated to the latest version. I provide the crash log and the latest log. 

### What was the expected result?

Any mob kills me (any mob at all), and the game crashes

### Steps to Reproduce

As far as I understand, the error occurs when updating a mob after it kills me, but I can’t say exactly what the reason might be, most likely it’s some kind of incompatibility with another mod

### Log Output (if applicable)

[latest.log](https://github.com/Zepalesque/The-Aether-Redux/files/14833402/latest.log)

### Crash Report (if applicable)

[crash-2024-04-01_23.02.14-server.txt](https://github.com/Zepalesque/The-Aether-Redux/files/14833403/crash-2024-04-01_23.02.14-server.txt)

### Is this a compatibility issue with another mod?

Most likely yes, but I can't find it yet

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
I will note that this update was an april fools update, and i plan to release the actual next version soon lol

but in the event that i copy some of the stuff over to a separate addon i will look into it
