### ISSUE TITLE
[Bug]: Broken Leaves Loot Table

### ISSUE THREAD

**Issue by bolobread** [Zepalesque/Aether-Redux-Issue-Tracker#97]
### Minecraft Version

1.19.2

### Mod Version

2.0.8

### Forge/Neoforge Version

43.3.0

### What happened?

All the leaf blocks use `any_of` instead of `alternative` in their loot table, which effectively breaks the loot table. discovered using neruina.

### What was the expected result?

The leaves should be dropping items and not crashing my game. Attached are the fixed loot tables.
[azure_fieldsproot_leaves.json](https://github.com/Zepalesque/The-Aether-Redux/files/14865289/azure_fieldsproot_leaves.json)
[blighted_skyroot_leaves.json](https://github.com/Zepalesque/The-Aether-Redux/files/14865290/blighted_skyroot_leaves.json)
[blightwillow_leaves.json](https://github.com/Zepalesque/The-Aether-Redux/files/14865291/blightwillow_leaves.json)
[fieldsproot_leaves.json](https://github.com/Zepalesque/The-Aether-Redux/files/14865292/fieldsproot_leaves.json)
[gilded_oak_leaves.json](https://github.com/Zepalesque/The-Aether-Redux/files/14865293/gilded_oak_leaves.json)
[glacia_leaves.json](https://github.com/Zepalesque/The-Aether-Redux/files/14865294/glacia_leaves.json)
[prismatic_fieldsproot_leaves.json](https://github.com/Zepalesque/The-Aether-Redux/files/14865295/prismatic_fieldsproot_leaves.json)
[purple_glacia_leaves.json](https://github.com/Zepalesque/The-Aether-Redux/files/14865296/purple_glacia_leaves.json)
[spectral_fieldsproot_leaves.json](https://github.com/Zepalesque/The-Aether-Redux/files/14865297/spectral_fieldsproot_leaves.json)

### Steps to Reproduce

Take a look at lines 19, 75 and 143 of the loot tables for all leaves in the mod.

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
ah yeah oops
will be fixed in 2.0.9

**Comment by Zepalesque** [comment]
ok this is fixed now

**Comment by bolobread** [comment]
This issue has brought itself back in the newest update somehow. it appears that in the new loot tables for all the leaves, all the `"type": "minecraft:alternatives"` and `"condition": "minecraft:alternative"` have been changed to `alternatives` which breaks the loot tables again

**Comment by bolobread** [comment]
more specifically, in 1.19.2, leaves use `"minecraft:alternative"` for the loot table, but in 1.20.1 it uses `"minecraft:any_of"`

**Comment by Zepalesque** [comment]
aaah whoops :joy:

**Comment by Zepalesque** [comment]
OH
ok
I accidentally did `minecraft:alternatives` instead of `minecraft:alternative` lol

**Comment by Zepalesque** [comment]
~~oh wait you said that im blind xd~~

**Comment by bolobread** [comment]
nah ur good, im just making a modpack but am catching errors in the logs

**Comment by Zepalesque** [comment]
ok yeah this should be fixed now, as of 2.0.13
