### ISSUE TITLE
[Bug]: Loading crash

### ISSUE THREAD

**Issue by idrinkmotoroil** [Zepalesque/Aether-Redux-Issue-Tracker#98]
### Minecraft Version

1.20.1

### Mod Version

2.0.8

### Forge/Neoforge Version

47.2.20

### What happened?

The mod fails to load correctly and gives this error:
![2024-04-06_23 00 46](https://github.com/Zepalesque/The-Aether-Redux/assets/166244995/e38631a2-f0ab-4953-8020-73d2fa1dd536)

### What was the expected result?

Not fail to load correctly

### Steps to Reproduce

Launch Minecraft

### Log Output (if applicable)

[2024-04-06-7.log](https://github.com/Zepalesque/The-Aether-Redux/files/14894546/2024-04-06-7.log)

### Crash Report (if applicable)

[crash-2024-04-06_23.06.53-fml.txt](https://github.com/Zepalesque/The-Aether-Redux/files/14894547/crash-2024-04-06_23.06.53-fml.txt)

### Is this a compatibility issue with another mod?

Probably

### Additional Context/Information

This might be a compatibility issue because i want to use it in modpack with 170 other mods. Since this is a loading issue i tried to remove some mods that speed up the loading process, but it didn't help.

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
Try updating your Aether version, this appears to be due to a feature from a recent Aether update not being present
